services:
  beets:
    build: .
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - SSH_PASSWORD=changeme
      - SSH_PORT=2222
    volumes:
      - /host-config:/config
      - /host-music:/music
      - /host-downloads:/downloads
    ports:
      - "8337:8337"  # Beets web interface
      - "2222:2222"  # SSH server
    restart: unless-stopped
